<a href="https://colab.research.google.com/github/Anissa-Atifa/BigData/blob/main/BigData2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**INSTALLASI DAN PENGGUNAAN PANDAS**

Untuk menginstall Pandas, kita bisa mengimport dan cek versinya

In [5]:
import pandas
pandas.__version__

'1.1.5'

Sama seperti kita biasanya mengimpor NumPy di bawah alias np, kita akan mengimpor Pandas di bawah
alias pd:

In [6]:
import numpy as np
import pandas as pd

**Memperkenalkan Objek Pandas**

**The Pandas Series Object**

Seri Pandas adalah larik satu dimensi dari data yang diindeks. Itu dapat dibuat dari a
daftar atau larik sebagai berikut: 

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

Seperti yang kita lihat pada keluaran sebelumnya, Seri membungkus urutan nilai dan a
urutan indeks, yang dapat kita akses dengan nilai dan atribut indeks. Itu
nilai hanyalah array NumPy yang sudah dikenal:

In [8]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

Indeks adalah objek mirip larik berjenis pd.Index, yang akan kita bahas lebih detail
sesaat:

In [9]:
data.index

RangeIndex(start=0, stop=4, step=1)

Seperti dengan array NumPy, data dapat diakses oleh indeks terkait melalui familiar
Notasi kurung siku Python:

In [10]:
data[1]

0.5

In [11]:
data[1:3]

1    0.50
2    0.75
dtype: float64

Seperti yang akan kita lihat, Seri Pandas jauh lebih umum dan fleksibel daripada
array NumPy satu dimensi yang diemulasinya.

**Series as generalized NumPy array**

Definisi indeks eksplisit ini memberikan kemampuan tambahan pada objek Seri. Misalnya, indeks tidak harus berupa bilangan bulat, tetapi dapat terdiri dari nilai apa pun yang diinginkan
Tipe. Misalnya, jika kita mau, kita bisa menggunakan string sebagai indeks: 


In [12]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

Dan akses item berfungsi seperti yang diharapkan:

In [13]:
data['b']

0.5

Kita bahkan dapat menggunakan indeks yang tidak bersebelahan atau tidak penting:

In [14]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [15]:
data[5]

0.5

**Series as specialized dictionary**

Kita dapat membuat analogi Seri-sebagai-kamus menjadi lebih jelas dengan membuat sebuah Objek seri langsung dari kamus Python:

In [16]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552868,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552868
Illinois      12882135
dtype: int64

Secara default, Seri akan dibuat di mana indeks diambil dari kunci yang diurutkan.
Dari sini, akses item bergaya kamus dapat dilakukan:

In [17]:
population['California']

38332521

Tidak seperti kamus, Seri juga mendukung operasi gaya array seperti
mengiris:

In [18]:
population['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552868
Illinois      12882135
dtype: int64

**Constructing Series objects**

Indeks adalah argumen opsional, dan data bisa menjadi salah satu dari banyak entitas.
Misalnya, data dapat berupa daftar atau array NumPy, dalam hal ini indeks default ke urutan bilangan bulat: 

In [ ]:
>>> pd.Series(data, index=index)

In [19]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

data dapat berupa skalar, yang diulangi untuk mengisi indeks yang ditentukan:

In [20]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

data bisa berupa kamus, di mana indeks default ke kunci kamus yang diurutkan:

In [21]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

Dalam setiap kasus, indeks dapat disetel secara eksplisit jika hasil yang berbeda lebih disukai:

In [22]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

Perhatikan bahwa dalam kasus ini, Seri hanya diisi dengan yang diidentifikasi secara eksplisit
kunci.

**The Pandas DataFrame Object**

**DataFrame as a generalized NumPy array**

Jika Seri adalah analog dari larik satu dimensi dengan indeks fleksibel, DataFrame
adalah analog dari larik dua dimensi dengan indeks baris fleksibel dan fleksibel
nama kolom.

Untuk mendemonstrasikan ini, pertama-tama mari kita buat Seri baru yang mencantumkan luas masing-masing
lima keadaan yang dibahas di bagian sebelumnya: 

In [23]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

Sekarang kita memiliki ini bersama dengan Seri populasi dari sebelumnya, kita dapat menggunakan a
kamus untuk membuat objek dua dimensi tunggal yang berisi informasi ini:

In [24]:
states = pd.DataFrame({'population': population,
                       'area': area})
states


population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552868  170312
Illinois      12882135  149995

Seperti objek Seri, DataFrame memiliki atribut indeks yang memberikan akses ke
label indeks:

In [25]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

Selain itu, DataFrame memiliki atribut kolom, yang merupakan objek Indeks yang dipegang
label kolom:

In [26]:
states.columns

Index(['population', 'area'], dtype='object')

Dengan demikian DataFrame dapat dianggap sebagai generalisasi dua dimensi
Array NumPy, di mana baris dan kolom memiliki indeks umum untuk akses mengambil data.

**DataFrame as specialized dictionary**

Demikian pula, kita juga bisa menganggap DataFrame sebagai spesialisasi kamus. Dimana
kamus memetakan kunci ke nilai, DataFrame memetakan nama kolom ke Seri
data kolom. Misalnya, meminta atribut 'area' mengembalikan objek Seri
berisi area yang kita lihat sebelumnya:

In [27]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

**Constructing Dataframe Objects**

**Dari satu objek Seri**

 DataFrame adalah kumpulan objek Seri, dan satu kolom DataFrame dapat dibuat dari Seri tunggal:

In [28]:
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552868
Illinois      12882135

**From List of Dictionary**

Daftar kamus apa pun dapat dibuat menjadi DataFrame. Kita akan menggunakan
pemahaman daftar sederhana untuk membuat beberapa data: 

In [29]:
import pandas as pd
data = [{'a': i, 'b': 2*i}
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

Meskipun beberapa kunci dalam kamus hilang, Panda akan mengisinya dengan NaN (mis.,
"Bukan angka"):

In [30]:
pd.DataFrame([{'a': 1, 'b': 2},
              {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

**From a dictionary of Series Objects**

In [31]:
pd.DataFrame({'population': population,
              'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552868  170312
Illinois      12882135  149995

**From a two-dimensional NumPyrray**

Diberikan array data dua dimensi, kita bisa
buat DataFrame dengan kolom dan nama indeks tertentu. Jika dihilangkan, bilangan bulat
indeks akan digunakan untuk masing-masing:

In [32]:
pd.DataFrame(np.random.rand(3, 2),
 columns=['foo', 'bar'],
 index=['a', 'b', 'c'])

foo       bar
a  0.357757  0.797124
b  0.602200  0.000312
c  0.553671  0.196626

**From a Numpy structured array**

A Pandas DataFrame beroperasi seperti file
array terstruktur, dan dapat dibuat langsung dari satu:

In [33]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [34]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

**Objek Indeks Pandas**

Objek Indeks ini menarik
struktur itu sendiri, dan dapat dianggap sebagai larik yang tidak dapat diubah atau sebagai
set terurut (secara teknis multiset, karena objek Indeks mungkin berisi nilai yang berulang).
Pandangan tersebut memiliki beberapa konsekuensi menarik dalam operasi yang tersedia di Index
benda. Sebagai contoh sederhana, mari kita buat Indeks dari daftar bilangan bulat:

In [35]:
ind = pd.Index([2, 3, 5, 7, 11])
ind


Int64Index([2, 3, 5, 7, 11], dtype='int64')

**IndeksArray tidak dapat diubah**

Objek Indeks dalam banyak hal beroperasi seperti array. Misalnya, kita bisa menggunakan stan‐
notasi pengindeksan dard Python untuk mengambil nilai atau irisan:

In [36]:
ind[1]

3

In [37]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

Objek indeks juga memiliki banyak atribut yang familiar dari array NumPy:

In [38]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


Satu perbedaan antara objek Indeks dan array NumPy adalah bahwa indeks adalah tidak dapat diubah artinya, mereka tidak dapat dimodifikasi melalui cara biasa:

In [39]:
ind[1] = 0

TypeError: ignored

Kekekalan ini membuatnya lebih aman untuk berbagi indeks antara beberapa DataFrame dan
array, tanpa potensi efek samping dari modifikasi indeks yang tidak disengaja.

**Index as Ordered set**

Objek Pandas dirancang untuk memfasilitasi operasi seperti penggabungan di seluruh kumpulan data,
yang bergantung pada banyak aspek himpunan aritmatika. Objek Index mengikuti banyak konvensi yang digunakan oleh struktur data set bawaan Python, sehingga persatuan, persimpangan, perbedaan, dan kombinasi lain dapat dihitung dengan cara yang familiar:

In [40]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [41]:
indA & indB # intersection

Int64Index([3, 5, 7], dtype='int64')

In [42]:
indA | indB # union

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [43]:
indA ^ indB # symmetric difference

Int64Index([1, 2, 9, 11], dtype='int64')

Operasi ini juga dapat diakses melalui metode objek. misalnya, in.intersection (imdB).

**Data Indexing and Selection**

**Data Selection in Series**

**Series as Dictionary**


Seperti kamus, objek Seri menyediakan pemetaan dari kumpulan kunci ke a
kumpulan nilai:

In [45]:

data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [46]:
data['b']

0.5

Kita juga dapat menggunakan ekspresi dan metode Python seperti kamus untuk memeriksa
kunci / indeks dan nilai:

In [47]:
'a' in data

True

In [48]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [49]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

Objek seri bahkan dapat dimodifikasi dengan sintaks seperti kamus. Seperti yang Anda bisa
memperluas kamus dengan menetapkan ke kunci baru, Anda dapat memperluas Seri dengan menetapkan
ke nilai indeks baru:

In [50]:
data['e']=1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

Perubahan objek yang mudah ini adalah fitur yang nyaman: di bawah tenda, Pandas ada
membuat keputusan tentang tata letak memori dan penyalinan data yang mungkin perlu dilakukan
tempat; pengguna umumnya tidak perlu khawatir tentang masalah ini.

**Series as one-dimensional array**

Seri A dibangun di atas antarmuka seperti kamus ini dan menyediakan pemilihan item bergaya larik
tion melalui mekanisme dasar yang sama seperti array NumPy — yaitu, slice, masking, dan pengindeksan mewah. Contohnya adalah sebagai berikut:

In [51]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [52]:
#slicing by implicit integerindex
data[0:2]

a    0.25
b    0.50
dtype: float64

In [53]:
# masking
data[(data > 0.3) & (data < 0.8)]


b    0.50
c    0.75
dtype: float64

In [54]:
#fancy indexing
data[['a','b']]

a    0.25
b    0.50
dtype: float64

**Indexers:loc,iloc, andix**

Konvensi pemotongan dan pengindeksan ini dapat menjadi sumber kebingungan. Misalnya, jika
Seri Anda memiliki indeks integer eksplisit, operasi pengindeksan seperti data [1] akan melakukannya
menggunakan indeks eksplisit, sementara operasi pemotongan seperti data [1: 3] akan menggunakan implisit
Indeks gaya Python.

In [55]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data


1    a
3    b
5    c
dtype: object

In [56]:
#explicit index when slicing
data[1:3]

3    b
5    c
dtype: object

Pertama, atribut loc memungkinkan pengindeksan dan pemotongan yang selalu mereferensikan eksplisit
indeks:

In [57]:
data.loc[1]

'a'

In [58]:
data.loc[1:3]

1    a
3    b
dtype: object

**Data Selection in DataFrame**

**DataFrame as a dictionary**

In [59]:
area = pd.Series({'California': 423967, 'Texas': 695662,
'New York': 141297, 'Florida': 170312,
'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

Seri individu yang membentuk kolom DataFrame dapat diakses
melalui pengindeksan gaya kamus dari nama kolom:

In [60]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Sama halnya, kita bisa menggunakan akses bergaya atribut dengan nama kolom yang berupa string:

In [61]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Akses kolom bergaya atribut ini sebenarnya mengakses objek yang sama persis dengan
akses bergaya kamus:

In [62]:
data.area is data['area']

True

Misalnya, DataFrame memiliki metode pop (), jadi data.pop akan menunjuk ke ini daripada
kolom "pop":

In [63]:
data.pop is data['pop']

False

Seperti objek Seri yang dibahas sebelumnya, sintaks gaya kamus ini juga bisa
digunakan untuk memodifikasi objek, dalam hal ini menambahkan kolom baru:

In [64]:
data['density'] = data['pop'] / data['area']
data


area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

**DataFrame as two-dimensional array**

Seperti disebutkan sebelumnya, kita juga dapat melihat DataFrame sebagai array dua dimensi yang disempurnakan. Kita dapat memeriksa larik data mentah yang mendasari menggunakan nilai
atribut:

In [65]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [66]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [67]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [68]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Jadi untuk pengindeksan gaya array, kita membutuhkan konvensi lain. Di sini Panda menggunakan lagi
pengindeks loc, iloc, dan ix yang disebutkan sebelumnya. Menggunakan pengindeks iloc, kami bisa
indeks array yang mendasari seolah-olah itu adalah array NumPy sederhana (menggunakan implisit
Python-style index), tetapi indeks DataFrame dan label kolom dipertahankan di
hasil:

In [69]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [74]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [77]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [78]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [79]:
data.iloc[0,2]=90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

**Additional Indexing Conventions**

Ada beberapa konvensi pengindeksan tambahan yang mungkin tampak bertentangan dengan pembahasan sebelumnya, namun dapat sangat berguna dalam praktiknya. Pertama, saat pengindeksan mengacu pada kolom, pemotongan mengacu pada baris:

In [80]:
data['Florida':'Illinois']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [81]:
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [82]:
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

**Operating on Data in Pandas**

**Ufuncs:Index Preservation**

Karena Pandas dirancang untuk bekerja dengan NumPy, semua ufunc NumPy akan bekerja
Seri Pandas dan objek DataFrame. Mari kita mulai dengan mendefinisikan Rangkaian sederhana dan
DataFrame untuk mendemonstrasikan ini:

In [83]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [84]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [85]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [86]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

**UFuncs:Index Alignment**

**Index alignment in Series**

Sebagai contoh, misalkan kita menggabungkan dua sumber data yang berbeda, dan hanya menemukan
tiga teratas negara bagian AS menurut wilayah dan tiga negara bagian AS teratas menurut populasi:

In [88]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127}, name='population')


In [89]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [90]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [91]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [92]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

**Index aligment in DataFrame**

Jenis perataan serupa terjadi untuk kolom dan indeks saat Anda berada
melakukan operasi pada DataFrames:

In [93]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [94]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
columns=list('BAC'))
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [95]:
A+B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [96]:
fill = A.stack().mean()
A.add(B, fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

**Ufuncs : Operations Between DataFrameand Series**

Pertimbangkan satu operasi umum, di mana kami menemukan perbedaan dari a
array dua dimensi dan salah satu barisnya:

In [ ]:
df = pd.DataFrame(A, columns=list('QRST'))
 df - df.iloc[0]

In [97]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [98]:
A-A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [99]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [100]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [101]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int64

In [102]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

**Handling Missing Data**

**Trade-Offs in Missing Data Conventions**

Dalam pendekatan masking, mask mungkin merupakan array Boolean yang sepenuhnya terpisah, atau itu
mungkin melibatkan penggunaan satu bit dalam representasi data untuk menunjukkan secara lokal
status nol dari suatu nilai.


**Missing Data in Pandas**


**None: Pythonic missing Data**

Nilai sentinel pertama yang digunakan oleh Pandas adalah None, objek tunggal Python yang sering digunakan
digunakan untuk data yang hilang dalam kode Python. Karena None adalah objek Python, maka tidak mungkin
digunakan dalam larik NumPy / Pandas sembarang, tetapi hanya dalam larik dengan tipe data
'object' (yaitu, array objek Python):

In [103]:
vals1 = np.array([1, None, 3, 4])
vals1


array([1, None, 3, 4], dtype=object)

In [106]:
vals1.sum()

TypeError: ignored

**NaN: Missing numerical data**

Representasi data lain yang hilang, NaN (singkatan dari Not a Number), berbeda;
ini adalah nilai floating-point khusus yang dikenali oleh semua sistem yang menggunakan standar
Representasi floating-point IEEE:

In [107]:
vals2 = np.array([1, np.nan, 3, 4])
vals2.dtype

dtype('float64')

In [108]:
1 + np.nan

nan

In [109]:
0 + np.nan

nan

In [110]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [111]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

Ingatlah bahwa NaN secara khusus adalah nilai floating-point; tidak ada yang setara
Nilai NaN untuk bilangan bulat, string, atau jenis lainnya.

**NaN and None in Pandas**

In [112]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [113]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [114]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

**Operating on Null Values**


 Pandas memperlakukan None dan NaN sebagai dasarnya dapat dipertukarkan untuk indintifikasi nilai yang hilang atau nol. Untuk memfasilitasi konvensi ini, ada beberapa yang berguna
metode untuk mendeteksi, menghapus, dan mengganti nilai null dalam struktur data Pandas yaitu:

isnull ()
Buat topeng Boolean yang menunjukkan nilai yang hilang

notnull ()
Kebalikan dari isnull ()

dropna ()
Kembalikan versi data yang difilter

fillna ()
Kembalikan salinan data dengan nilai yang hilang diisi atau diperhitungkan

Kami akan mengakhiri bagian ini dengan eksplorasi singkat dan demonstrasi ini
rutinitas.

**Detecting null values**

In [115]:
data = pd.Series([1, np.nan, 'hello', None])

In [116]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [117]:
data[data.notnull()]

0        1
2    hello
dtype: object

**Dropping null values**

Selain masking yang digunakan sebelumnya, ada metode kemudahan, dropna ()
(yang menghapus nilai NA) dan fillna () (yang mengisi nilai NA). Untuk Seri,
hasilnya langsung:


In [118]:
data.dropna()

0        1
2    hello
dtype: object

In [119]:
df = pd.DataFrame([[1, np.nan, 2],
[2, 3, 5],
[np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [120]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [121]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [122]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [123]:
df.dropna(axis='columns', how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [124]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

Sebelum baris pertama dan terakhir telah dihapus, karena baris tersebut hanya berisi dua nilai bukan nol.